### ISSUE TITLE
Can't run project

### ISSUE THREAD

**Issue by thomasmodeneis** [nsf/gocovgui#3]
Any ideas ?

```
$ go run main.go 
# github.com/nsf/gothic
ld: library not found for -ltcl8.6
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nsf** [comment]
Well, the message says it all: `ld: library not found for -ltcl8.6`

I don't recommend using gocovgui. These days native go tool generates nice HTML files with coverage info. You don't need gocovgui anymore. Not to mention that gocov tool itself is not relevant anymore as coverage analysis is a built-in feature of go's ecosystem.

**Comment by thomasmodeneis** [comment]
I see.. thanks @nsf have a nice week.
